### root domain test
GET http://localhost:8000/

###### Admin API ###
## get admin api
GET http://localhost:8000/api/v1/admin/


### post admin api
POST http://localhost:8000/api/v1/admin
Content-Type: application/json

{
 "fName":"Dipak",
 "lName":"Paudel",
 "dob":"2020-08-01",
 "email":"paudelsantosh508@gmail.com",
 "phone":"0452450087",
 "password":"Dipak1234",
 "address":"3/25Cecilstreet"

}


### post admin api
POST http://localhost:8000/api/v1/admin/email-verification
Content-Type: application/json

{
  "email" : "admin@jhkj.bb",
  "emailValidationCode" : "fac5f0c5-a67f-414f-88a6-0f9d72267d33"
}

### login admin api
POST http://localhost:8000/api/v1/admin/login
Content-Type: application/json

{
  "email" : "admin@jhkj.bb",
  "password":"helloworld"
}

### patch admin api
PATCH   http://localhost:8000/api/v1/admin/

