import express from "express";
const router = express.Router();

const orderArgs = [
  {
    _id: "1",
    status: "processing",
    buyers: {
      buyer: "asdf",
      buyerId: "asdf",
      fName: "adsffs",
      lName: "paudel",
      email: "paudelsantosh508@gmail.com",
      phone: "8990302309",
    },
    cart: [
      {
        productId: "12",
        productName: "falfull",
        salesPrice: "5",
        qty: "5",
        thumbnail: "http://",
        subTotal: 333,
      },
    ],
    cartTotal: "adf",
    discount: 50,
    discountCode: "50off",
    totalAmount: "54",
    paymentInfo: {
      status: "pending",
      method: "cash on pickup",
      paidAmount: "453",
      transactionId: "adfd",
      paidDate: "10/10/2021",
    },
  },
  {
    _id: "2",
    status: "pending",
    buyers: {
      buyer: "asdf",
      buyerId: "asdf",
      fName: "adsffs",
      lName: "paudel",
      email: "paudelsantosh508@gmail.com",
      phone: "8990302309",
    },
    cart: [
      {
        productId: "12",
        productName: "falfull",
        salesPrice: "5",
        qty: "5",
        thumbnail: "http://",
        subTotal: 333,
      },
    ],
    cartTotal: "adf",
    discount: 50,
    discountCode: "50off",
    totalAmount: "54",
    paymentInfo: {
      status: "pending",
      method: "cash on pickup",
      paidAmount: "453",
      transactionId: "adfd",
      paidDate: "10/10/2021",
    },
  },
  {
    _id: "3",
    status: "shipped",
    buyers: {
      buyer: "asdf",
      buyerId: "asdf",
      fName: "adsffs",
      lName: "paudel",
      email: "paudelsantosh508@gmail.com",
      phone: "8990302309",
    },
    cart: [
      {
        productId: "12",
        productName: "falfull",
        salesPrice: "5",
        qty: "5",
        thumbnail: "http://",
        subTotal: 333,
      },
    ],
    cartTotal: "adf",
    discount: 50,
    discountCode: "50off",
    totalAmount: "54",
    paymentInfo: {
      status: "pending",
      method: "cash on pickup",
      paidAmount: "453",
      transactionId: "adfd",
      paidDate: "10/10/2021",
    },
  },
  {
    _id: "4",
    status: "cancelled",
    buyers: {
      buyer: "asdf",
      buyerId: "asdf",
      fName: "adsffs",
      lName: "paudel",
      email: "paudelsantosh508@gmail.com",
      phone: "8990302309",
    },
    cart: [
      {
        productId: "12",
        productName: "falfull",
        salesPrice: "5",
        qty: "5",
        thumbnail: "http://",
        subTotal: 333,
      },
    ],
    cartTotal: "adf",
    discount: 50,
    discountCode: "50off",
    totalAmount: "54",
    paymentInfo: {
      status: "pending",
      method: "cash on pickup",
      paidAmount: "453",
      transactionId: "adfd",
      paidDate: "10/10/2021",
    },
  },
  {
    _id: "5",
    status: "processing",
    buyers: {
      buyer: "asdf",
      buyerId: "asdf",
      fName: "adsffs",
      lName: "paudel",
      email: "paudelsantosh508@gmail.com",
      phone: "8990302309",
    },
    cart: [
      {
        productId: "12",
        productName: "falfull",
        salesPrice: "5",
        qty: "5",
        thumbnail: "http://",
        subTotal: 333,
      },
    ],
    cartTotal: "adf",
    discount: 50,
    discountCode: "50off",
    totalAmount: "54",
    paymentInfo: {
      status: "pending",
      method: "cash on pickup",
      paidAmount: "453",
      transactionId: "adfd",
      paidDate: "10/10/2021",
    },
  },
  {
    _id: "6",
    status: "pending",
    buyers: {
      buyer: "asdf",
      buyerId: "asdf",
      fName: "adsffs",
      lName: "paudel",
      email: "paudelsantosh508@gmail.com",
      phone: "8990302309",
    },
    cart: [
      {
        productId: "12",
        productName: "falfull",
        salesPrice: "5",
        qty: "5",
        thumbnail: "http://",
        subTotal: 333,
      },
    ],
    cartTotal: "adf",
    discount: 50,
    discountCode: "50off",
    totalAmount: "54",
    paymentInfo: {
      status: "pending",
      method: "cash on pickup",
      paidAmount: "453",
      transactionId: "adfd",
      paidDate: "10/10/2021",
    },
  },
  {
    _id: "7",
    status: "shipped",
    buyers: {
      buyer: "asdf",
      buyerId: "asdf",
      fName: "adsffs",
      lName: "paudel",
      email: "paudelsantosh508@gmail.com",
      phone: "8990302309",
    },
    cart: [
      {
        productId: "12",
        productName: "falfull",
        salesPrice: "5",
        qty: "5",
        thumbnail: "http://",
        subTotal: 333,
      },
    ],
    cartTotal: "adf",
    discount: 50,
    discountCode: "50off",
    totalAmount: "54",
    paymentInfo: {
      status: "pending",
      method: "cash on pickup",
      paidAmount: "453",
      transactionId: "adfd",
      paidDate: "10/10/2021",
    },
  },
  {
    _id: "8",
    status: "cancelled",
    buyers: {
      buyer: "asdf",
      buyerId: "asdf",
      fName: "adsffs",
      lName: "paudel",
      email: "paudelsantosh508@gmail.com",
      phone: "8990302309",
    },
    cart: [
      {
        productId: "12",
        productName: "falfull",
        salesPrice: "5",
        qty: "5",
        thumbnail: "http://",
        subTotal: 333,
      },
    ],
    cartTotal: "adf",
    discount: 50,
    discountCode: "50off",
    totalAmount: "54",
    paymentInfo: {
      status: "pending",
      method: "cash on pickup",
      paidAmount: "453",
      transactionId: "adfd",
      paidDate: "10/10/2021",
    },
  },
  {
    _id: "9",
    status: "processing",
    buyers: {
      buyer: "asdf",
      buyerId: "asdf",
      fName: "adsffs",
      lName: "paudel",
      email: "paudelsantosh508@gmail.com",
      phone: "8990302309",
    },
    cart: [
      {
        productId: "12",
        productName: "falfull",
        salesPrice: "5",
        qty: "5",
        thumbnail: "http://",
        subTotal: 333,
      },
    ],
    cartTotal: "adf",
    discount: 50,
    discountCode: "50off",
    totalAmount: "54",
    paymentInfo: {
      status: "pending",
      method: "cash on pickup",
      paidAmount: "453",
      transactionId: "adfd",
      paidDate: "10/10/2021",
    },
  },
  {
    _id: "10",
    status: "pending",
    buyers: {
      buyer: "asdf",
      buyerId: "asdf",
      fName: "adsffs",
      lName: "paudel",
      email: "paudelsantosh508@gmail.com",
      phone: "8990302309",
    },
    cart: [
      {
        productId: "12",
        productName: "falfull",
        salesPrice: "5",
        qty: "5",
        thumbnail: "http://",
        subTotal: 333,
      },
    ],
    cartTotal: "adf",
    discount: 50,
    discountCode: "50off",
    totalAmount: "54",
    paymentInfo: {
      status: "pending",
      method: "cash on pickup",
      paidAmount: "453",
      transactionId: "adfd",
      paidDate: "10/10/2021",
    },
  },
  {
    _id: "11",
    status: "shipped",
    buyers: {
      buyer: "asdf",
      buyerId: "asdf",
      fName: "adsffs",
      lName: "paudel",
      email: "paudelsantosh508@gmail.com",
      phone: "8990302309",
    },
    cart: [
      {
        productId: "12",
        productName: "falfull",
        salesPrice: "5",
        qty: "5",
        thumbnail: "http://",
        subTotal: 333,
      },
    ],
    cartTotal: "adf",
    discount: 50,
    discountCode: "50off",
    totalAmount: "54",
    paymentInfo: {
      status: "pending",
      method: "cash on pickup",
      paidAmount: "453",
      transactionId: "adfd",
      paidDate: "10/10/2021",
    },
  },
  {
    _id: "12",
    status: "cancelled",
    buyers: {
      buyer: "asdf",
      buyerId: "asdf",
      fName: "adsffs",
      lName: "paudel",
      email: "paudelsantosh508@gmail.com",
      phone: "8990302309",
    },
    cart: [
      {
        productId: "12",
        productName: "falfull",
        salesPrice: "5",
        qty: "5",
        thumbnail: "http://",
        subTotal: 333,
      },
    ],
    cartTotal: "adf",
    discount: 50,
    discountCode: "50off",
    totalAmount: "54",
    paymentInfo: {
      status: "pending",
      method: "cash on pickup",
      paidAmount: "453",
      transactionId: "adfd",
      paidDate: "10/10/2021",
    },
  },
];

router.get("/:_id?", async (req, res, next) => {
  try {
    const { _id } = req.params;
    const orders = _id
      ? orderArgs.filter((item) => item._id === _id)
      : orderArgs;
    res.json({
      status: "success",
      message: "customer list",
      orders,
    });
  } catch (error) {
    next(error);
  }
});

export default router;
